CREATE DATABASE abc_orders;

USE abc_orders;

SELECT*
FROM orders
LIMIT 10;

DESCRIBE orders;
DESCRIBE products;
DESCRIBE account;

SET SQL_SAFE_UPDATES = 0;

UPDATE orders
SET order_date = STR_TO_DATE(order_date, '%m/%d/%Y'),
ship_date = STR_TO_DATE(ship_date, '%m/%d/%Y');

ALTER TABLE orders
MODIFY COLUMN order_date date, 
MODIFY COLUMN ship_date date;

SELECT COUNT(*)
FROM orders
WHERE order_no IS NULL;

SELECT order_no, COUNT(order_no) AS count_order_no
FROM orders
GROUP BY order_no
HAVING COUNT(order_no) > 1;

SELECT*
FROM orders
WHERE order_no = '5768-2' OR order_no = '6159-2';

SET SQL_SAFE_UPDATES= 1;

-- 1. What is the total revenue generated by each product category?
SELECT product_category,
		ROUND(SUM(total), 2) AS Revenue 
 FROM orders
 JOIN products
 ON orders.product_id = products.product_id
 GROUP BY product_category;
 
 -- 2.How many unique products have been ordered?
SELECT DISTINCT(COUNT(product_name)) AS Unique_Products
FROM products;

-- 3. What is the total revenue generated each year?
SELECT EXTRACT(YEAR from order_date) Year,
	FORMAT(SUM(total), 2) Revenue
FROM orders
GROUP BY Year;

-- 4. What is the date of the latest and earliest order?
SELECT MIN(order_date) 'Earliest Date',
	MAX(order_date) Latest_date
FROM orders;

-- 5. What product category has the lowest average price of products?
SELECT product_category,
	ROUND(AVG(retail_price), 2) Average_price
FROM orders
JOIN products
USING(product_id)
GROUP BY product_category
ORDER BY Average_price
LIMIT 1;

-- 6. What are the top 10 highest performing products?
SELECT product_name,
	ROUND(SUM(total), 2) Revenue
FROM orders
JOIN products
USING(product_id)
GROUP BY product_name
ORDER BY Revenue DESC
LIMIT 10;

-- 7. Show the total revenue and profit generated by each account_manager?
SELECT account_manager,
	ROUND(SUM(total), 2) Revenue,
        ROUND(SUM(total) - SUM(cost_price), 2) Profit
FROM orders
JOIN account
USING(account_id)
GROUP BY account_manager
ORDER BY Revenue DESC;

--  8. What is the name, city and account manager of the highest selling product in 2017?
SELECT product_name,
	city,
        account_manager,
        ROUND(SUM(total)) Revenue
FROM orders
JOIN products
USING(product_id)
JOIN account
USING(account_id)
WHERE EXTRACT(year from order_date) = 2017
GROUP BY product_name, city, account_manager
ORDER BY Revenue DESC
LIMIT 1;

-- 9. Find the mean amount spent per order by each Customer type?
SELECT customer_type,
	AVG(total) Average_amount
FROM orders
GROUP BY customer_type;
        
-- 10. What is the 5th highest selling product?
SELECT product_name, SUM(total) AS total_sales
FROM orders
JOIN products ON orders.product_id = products.product_id
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 1 OFFSET 4;

-- 11. What is the lowest selling product?
SELECT product_name, SUM(total) AS total_sales
FROM orders
JOIN products ON orders.product_id = products.product_id
GROUP BY product_name
ORDER BY total_sales ASC
LIMIT 1;

-- 12. What is the most profitable product?
SELECT product_name, 
       SUM(total - cost_price) AS total_profit
FROM orders
JOIN products ON orders.product_id = products.product_id
GROUP BY product_name
ORDER BY total_profit DESC
LIMIT 1;
